name: simply-just
recipe: lamp
config:
  webroot: public
  php: '7.4'

services:
  node:
    type: node
    build:
      - npm install

tooling:
  fix:
    service: appserver
    cmd: php vendor/bin/php-cs-fixer fix --verbose --allow-risky=yes
  npm:
    service: node
