title: Settings
data:
  site_name: 'Simply Just'
  social:
    -
      name: Twitter
      url: 'https://twitter.com/StepToMe_'
      icon: site/social-icons/twitter.svg
    -
      name: LinkedIn
      url: 'https://www.linkedin.com/in/dmlechkova'
      icon: site/social-icons/linkedin.svg
    -
      name: Github
      url: 'https://github.com/denitsa-md'
      icon: site/social-icons/github.svg
    -
      name: Email
      url: 'mailto:dmlechkova@gmail.com'
      icon: site/social-icons/email.svg
    -
      name: Goodreads
      url: 'https://www.goodreads.com/user/show/12825719-denitsa'
      icon: site/social-icons/goodreads.svg
